# NumPy

Numpy introduction
------------------

The NumPy package (read as NUMerical PYthon) provides access to

-   a new data structure called `array`s which allow

-   efficient vector and matrix operations. It also provides

-   a number of linear algebra operations (such as solving of systems of linear equations, computation of Eigenvectors and Eigenvalues).

### History

Some background information: There are two other implementations that provide nearly the same functionality as NumPy. These are called “Numeric” and “numarray”:

-   Numeric was the first provision of a set of numerical methods (similar to Matlab) for Python. It evolved from a PhD project.

-   Numarray is a re-implementation of Numeric with certain improvements (but for our purposes both Numeric and Numarray behave virtually identical).

-   Early in 2006 it was decided to merge the best aspects of Numeric and Numarray into the Scientific Python (<span>`scipy`</span>) package and to provide (a hopefully “final”) `array` data type under the module name “NumPy”.

We will use in the following materials the “NumPy” package as provided by (new) SciPy. If for some reason this doesn’t work for you, chances are that your SciPy is too old. In that case, you will find that either “Numeric” or “numarray” is installed and should provide nearly the same capabilities.[5]

### Arrays

We introduce a new data type (provided by NumPy) which is called “`array`”. An array *appears* to be very similar to a list but an array can keep only elements of the same type (whereas a list can mix different kinds of objects). This means arrays are more efficient to store (because we don’t need to store the type for every element). It also makes arrays the data structure of choice for numerical calculations where we often deal with vectors and matricies.

Vectors and matrices (and matrices with more than two indices) are all called “arrays” in NumPy.

#### Vectors (1d-arrays)

The data structure we will need most often is a vector. Here are a few examples of how we can generate one:

# Array Creation and Properties

There are a lot of ways to create arrays.  Let's look at a few

Here we create an array using `arange` and then change its shape to be 3 rows and 5 columns.

In [1]:
import numpy as np 

In [2]:
x = np.arange(10)
y = np.arange(12)

In [3]:
print(x)
y

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
c = np.arange(20).reshape(4,5)
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

A NumPy array has a lot of meta-data associated with it describing its shape, datatype, etc.

In [5]:
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(type(c))

2
(4, 5)
20
int32
4
<class 'numpy.ndarray'>


In [ ]:
help(c)

we can create an array from a list

In [6]:
c = np.array( [2.0, 6.0, 8.0] )
print(c)
print(c.dtype)
print(type(c))

[2. 6. 8.]
float64
<class 'numpy.ndarray'>


we can create a multi-dimensional array of a specified size initialized all to 0 easily.  There is also an analogous ones() and empty() array routine.  Note that here we explicitly set the datatype for the array. 

Unlike lists in python, all of the elements of a numpy array are of the same datatype

In [7]:
g = np.eye(8)
dtype = np.float64
g

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

`linspace` (and `logspace`) create arrays with evenly space (in log) numbers.  For `logspace`, you specify the start and ending powers (`base**start` to `base**stop`)

In [8]:
tom = np.linspace( -2, 3, 10, endpoint = True)
print(tom)

[-2.         -1.44444444 -0.88888889 -0.33333333  0.22222222  0.77777778
  1.33333333  1.88888889  2.44444444  3.        ]


In [9]:
f = np.logspace( -2, 3, 10, endpoint = True, base=10)
print(f)

[1.00000000e-02 3.59381366e-02 1.29154967e-01 4.64158883e-01
 1.66810054e+00 5.99484250e+00 2.15443469e+01 7.74263683e+01
 2.78255940e+02 1.00000000e+03]


As always, as for help -- the numpy functions have very nice docstrings

In [ ]:
help(np.logspace)

we can also initialize an array based on a function

In [10]:
g = np.fromfunction(lambda x,y: x==y,(4,4), dtype=int)
g

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

# Array Operations

most operations (`+`, `-`, `*`, `/`) will work on an entire array at once, element-by-element.

Note that that the multiplication operator is not a matrix multiply (there is a new operator in python 3.5+, `@`, to do matrix multiplicaiton.

Let's create a simply array to start with

In [11]:
y = np.arange(15).reshape(3,5)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Multiplication by a scalar multiplies every element

In [12]:
y*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

adding two arrays adds element-by-element

In [13]:
y + y

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

multiplying two arrays multiplies element-by-element

In [14]:
y * y

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

We can think of our 2-d array a was a 3 x 5 matrix (3 rows, 5 columns).  We can take the transpose to geta 5 x 3 matrix, and then we can do a matrix multiplication

In [15]:
print(y)
h = y.transpose()
h

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [16]:
y @ h

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

We can sum along axes or the entire array

In [17]:
print(y)
y.sum(axis=1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([10, 35, 60])

In [18]:
y.sum()

105

Also get the extrema

In [19]:
print(y.max(), y.min())

14 0


In [ ]:
### universal functions

Up until now, we have been discussing some of the basic nuts and bolts of NumPy; now, we will dive into the reasons that NumPy is so important in the Python data science world.
Namely, it provides an easy and flexible interface to optimized computation with arrays of data.

Computation on NumPy arrays can be very fast, or it can be very slow.
The key to making it fast is to use *vectorized* operations, generally implemented through NumPy's *universal functions* (ufuncs).
This section motivates the need for NumPy's ufuncs, which can be used to make repeated calculations on array elements much more efficient.
It then introduces many of the most common and useful arithmetic ufuncs available in the NumPy package.

universal functions work element-by-element.  Let's create a new array scaled by `pi`

In [20]:
k = y*np.pi/12.0
print(k)

[[0.         0.26179939 0.52359878 0.78539816 1.04719755]
 [1.30899694 1.57079633 1.83259571 2.0943951  2.35619449]
 [2.61799388 2.87979327 3.14159265 3.40339204 3.66519143]]


In [21]:
u = np.tan(y)
print(u)

[[ 0.00000000e+00  1.55740772e+00 -2.18503986e+00 -1.42546543e-01
   1.15782128e+00]
 [-3.38051501e+00 -2.91006191e-01  8.71447983e-01 -6.79971146e+00
  -4.52315659e-01]
 [ 6.48360827e-01 -2.25950846e+02 -6.35859929e-01  4.63021133e-01
   7.24460662e+00]]


In [22]:
z=k+u

In [23]:
print(z)

[[   0.            1.81920711   -1.66144109    0.64285162    2.20501883]
 [  -2.07151807    1.27979014    2.7040437    -4.70531635    1.90387883]
 [   3.26635471 -223.07105319    2.50573272    3.86641317   10.90979805]]


## Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this:
``` python
x[start:stop:step]
```
If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.
We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

In [24]:
h = np.arange(10)
h

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Now look at accessing a single element vs. a range (using slicing)

Giving a single (0-based) index just references a single value

In [25]:
h[7]

7

In [26]:
print(h[4:9])

[4 5 6 7 8]


In [27]:
h[5:8]

array([5, 6, 7])

In [28]:
h[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## Multidimensional Arrays

Multidimensional arrays are stored in a contiguous space in memory -- this means that the columns / rows need to be unraveled (flattened) so that it can be thought of as a single one-dimensional array.  Different programming languages do this via different conventions:


Storage order:

* Python/C use *row-major* storage: rows are stored one after the other
* Fortran/matlab use *column-major* storage: columns are stored one after another

The ordering matters when 

* passing arrays between languages (we'll talk about this later this semester)
* looping over arrays -- you want to access elements that are next to one-another in memory
  * e.g, in Fortran:
  <pre>
  double precision :: A(M,N)
  do j = 1, N
     do i = 1, M
        A(i,j) = …
     enddo
  enddo
  </pre>
  
  * in C
  <pre>
  double A[M][N];
  for (i = 0; i < M; i++) {
     for (j = 0; j < N; j++) {
        A[i][j] = …
     }
  }  
  </pre>
  

In python, using NumPy, we'll try to avoid explicit loops over elements as much as possible

Let's look at multidimensional arrays:

In [29]:
n = np.arange(12).reshape(4,3)
n

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Notice that the output of `a` shows the row-major storage.  The rows are grouped together in the inner `[...]`

Giving a single index (0-based) for each dimension just references a single value in the array

In [30]:
n[2,2]

8

Doing slices will access a range of elements.  Think of the start and stop in the slice as referencing the left-edge of the slots in the array.

In [31]:
n[0:3,0:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Access a specific column

In [32]:
n[:,2]

array([ 2,  5,  8, 11])

Sometimes we want a one-dimensional view into the array -- here we see the memory layout (row-major) more explicitly

In [33]:
n = n.flatten()
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


we can also iterate -- this is done over the first axis (rows)

In [34]:
#print (n)
for tom in n:
    print(tom)
n = np.arange(16).reshape(4,4)
print(n)

0
1
2
3
4
5
6
7
8
9
10
11
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


or element by element

In [35]:
for e in n.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [ ]:
help(n.flatten())

# Copying Arrays

simply using "=" does not make a copy, but much like with lists, you will just have multiple names pointing to the same ndarray object

Therefore, we need to understand if two arrays, `A` and `B` point to:
* the same array, including shape and data/memory space
* the same data/memory space, but perhaps different shapes (a _view_)
* a separate cpy of the data (i.e. stored completely separately in memory)

All of these are possible:
* `B = A`
  
  this is _assignment_.  No copy is made. `A` and `B` point to the same data in memory and share the same shape, etc.  They are just two different labels for the same object in memory
  

* `B = A[:]`

  this is a _view_ or _shallow copy_.  The shape info for A and B are stored independently, but both point to the same memory location for data
  
  
* `B = A.copy()`

  this is a _deep_ copy.  A completely separate object will be created in memory, with a completely separate location in memory.
  
Let's look at examples

In [36]:
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


Here is assignment -- we can just use the `is` operator to test for equality

In [37]:
f = e
f is e

True

Since `b` and `a` are the same, changes to the shape of one are reflected in the other -- no copy is made.

In [38]:
f.shape = (2,5)
print(f)
e.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [39]:
f is e

True

In [40]:
print(e)

[[0 1 2 3 4]
 [5 6 7 8 9]]


a shallow copy creates a new *view* into the array -- the data is the same, but the array properties can be different

In [41]:
a =np.arange(15)
c = a[:]
a.shape = (3,5)
print(a)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


since the underlying data is the same memory, changing an element of one is reflected in the other

In [42]:
c[1] = -1
print(a)
print(c)

[[ 0 -1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11 12 13 14]


Even slices into an array are just views, still pointing to the same memory

In [43]:
d = c[3:8]
print(d)

[3 4 5 6 7]


In [44]:
d[:] = 0

In [45]:
print(a)
print(c)
print(d)

[[ 0 -1  2  0  0]
 [ 0  0  0  8  9]
 [10 11 12 13 14]]
[ 0 -1  2  0  0  0  0  0  8  9 10 11 12 13 14]
[0 0 0 0 0]


There are lots of ways to inquire if two arrays are the same, views, own their own data, etc

In [46]:
print(c is a)
print(c.base is a)
print(c.flags.owndata)
print(a.flags.owndata)

False
True
False
True


to make a copy of the data of the array that you can deal with independently of the original, you need a deep copy

In [47]:
d = a.copy()
d[:,:] =  0.0
print(a)
print(d)

[[ 0 -1  2  0  0]
 [ 0  0  0  8  9]
 [10 11 12 13 14]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


# Boolean Indexing

There are lots of fun ways to index arrays to access only those elements that meet a certain condition

In [48]:
import numpy as np
x = np.arange(15).reshape(3,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Here we set all the elements in the array that are > 4 to zero

In [49]:
x[x<9] = 0
x

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  9],
       [10, 11, 12, 13, 14]])

In [50]:
x[x==0] = -1
x

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1,  9],
       [10, 11, 12, 13, 14]])

and now, all the zeros to -1

In [51]:
x == -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False, False, False, False]])

In [52]:
import numpy as np
x = np.arange(15).reshape(3,5)
print(x)
x[np.logical_and(x>5, x<=12)] = 0.0
x

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  0,  0,  0,  0],
       [ 0,  0,  0, 13, 14]])

if we have 2 tests, we need to use `logical_and()` or `logical_or()`

In [53]:
x<13

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True, False, False]])

Our test that we index the array with returns a boolean array of the same shape:

In [54]:
x>6

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

# Avoiding Loops

Python's default implementation (known as CPython) does some operations very slowly.
This is in part due to the dynamic, interpreted nature of the language: the fact that types are flexible, so that sequences of operations cannot be compiled down to efficient machine code as in languages like C and Fortran.
Recently there have been various attempts to address this weakness: well-known examples are the [PyPy](http://pypy.org/) project, a just-in-time compiled implementation of Python; the [Cython](http://cython.org) project, which converts Python code to compilable C code; and the [Numba](http://numba.pydata.org/) project, which converts snippets of Python code to fast LLVM bytecode.
Each of these has its strengths and weaknesses, but it is safe to say that none of the three approaches has yet surpassed the reach and popularity of the standard CPython engine.

The relative sluggishness of Python generally manifests itself in situations where many small operations are being repeated – for instance looping over arrays to operate on each element.

In general, you want to avoid loops over elements on an array.

Here, let's create 1-d x and y coordinates and then try to fill some larger array

In [55]:
import  numpy as np
a = 34
b = 44
xmin = ymin = 0.0
xmax = ymax = 2.0
m = np.linspace(xmin, ymax, a, endpoint=False)
n = np.linspace(xmin, ymax, b, endpoint=True)
print(m.shape)
print(n.shape)
n

(34,)
(44,)


array([0.        , 0.04651163, 0.09302326, 0.13953488, 0.18604651,
       0.23255814, 0.27906977, 0.3255814 , 0.37209302, 0.41860465,
       0.46511628, 0.51162791, 0.55813953, 0.60465116, 0.65116279,
       0.69767442, 0.74418605, 0.79069767, 0.8372093 , 0.88372093,
       0.93023256, 0.97674419, 1.02325581, 1.06976744, 1.11627907,
       1.1627907 , 1.20930233, 1.25581395, 1.30232558, 1.34883721,
       1.39534884, 1.44186047, 1.48837209, 1.53488372, 1.58139535,
       1.62790698, 1.6744186 , 1.72093023, 1.76744186, 1.81395349,
       1.86046512, 1.90697674, 1.95348837, 2.        ])

In [56]:
import time 
a = 34
b = 44
x = np.linspace(0.0, 2.0, a,endpoint=False)
n = np.linspace(0.0, 2.0, b, endpoint=True)

we'll time out code

In [57]:
t0 = time.time()
m = np.zeros((a,b))
for i in range(a):
    for j in range(b):
        m[i,j] = np.sin(2.0*np.pi*x[i]*n[j])
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0021162033081054688 s


In [58]:
x2d, y2d = np.meshgrid(x, n, indexing="ij" )
print(x2d[:,0])
print(x2d[0,:])
print(y2d[:,0])
print(y2d[0,:])

[0.         0.05882353 0.11764706 0.17647059 0.23529412 0.29411765
 0.35294118 0.41176471 0.47058824 0.52941176 0.58823529 0.64705882
 0.70588235 0.76470588 0.82352941 0.88235294 0.94117647 1.
 1.05882353 1.11764706 1.17647059 1.23529412 1.29411765 1.35294118
 1.41176471 1.47058824 1.52941176 1.58823529 1.64705882 1.70588235
 1.76470588 1.82352941 1.88235294 1.94117647]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.         0.04651163 0.09302326 0.13953488 0.18604651 0.23255814
 0.27906977 0.3255814  0.37209302 0.41860465 0.46511628 0.51162791
 0.55813953 0.60465116 0.65116279 0.69767442 0.74418605 0.79069767
 0.8372093  0.88372093 0.93023256 0.97674419 1.02325581 1.06976744
 1.11627907 1.1627907  1.20930233 1.25581395 1.30232558 1.34883721
 1.39534884 1.44186047 1.48837209 1.53488372 1.58139

Now let's instead do this using all array syntax.  First will extend our 1-d coordinate arrays to be 2-d

In [59]:
x2d, y2d = np.meshgrid(x, n, indexing="ij" )
print(x2d[:,0])
print(x2d[0,:])
print(y2d[:,0])
print(y2d[0,:])
print(y2d)

[0.         0.05882353 0.11764706 0.17647059 0.23529412 0.29411765
 0.35294118 0.41176471 0.47058824 0.52941176 0.58823529 0.64705882
 0.70588235 0.76470588 0.82352941 0.88235294 0.94117647 1.
 1.05882353 1.11764706 1.17647059 1.23529412 1.29411765 1.35294118
 1.41176471 1.47058824 1.52941176 1.58823529 1.64705882 1.70588235
 1.76470588 1.82352941 1.88235294 1.94117647]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0.         0.04651163 0.09302326 0.13953488 0.18604651 0.23255814
 0.27906977 0.3255814  0.37209302 0.41860465 0.46511628 0.51162791
 0.55813953 0.60465116 0.65116279 0.69767442 0.74418605 0.79069767
 0.8372093  0.88372093 0.93023256 0.97674419 1.02325581 1.06976744
 1.11627907 1.1627907  1.20930233 1.25581395 1.30232558 1.34883721
 1.39534884 1.44186047 1.48837209 1.53488372 1.58139

In [60]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0 s


## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations.
Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table.
Note that when constructing an array, they can be specified using a string:

```python
np.zeros(10, dtype='int16')
```

Or using the associated NumPy object:

```python
np.zeros(10, dtype=np.int16)
```

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

More advanced type specification is possible, such as specifying big or little endian numbers; for more information, refer to the [NumPy documentation](http://numpy.org/).
NumPy also supports compound data types, which will be covered in [Structured Data: NumPy's Structured Arrays](02.09-Structured-Data-NumPy.ipynb).

## Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

### Concatenation of arrays

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``.
``np.concatenate`` takes a tuple or list of arrays as its first argument, as we can see here:

In [61]:
tom = np.array([2,4,6,8])
jerry = np.array([3,5,7,9])
np.concatenate([jerry,tom])

array([3, 5, 7, 9, 2, 4, 6, 8])

You can also concatenate more than two arrays at once:

In [62]:
jack = [5,10,15,20]
print(np.concatenate([jack,tom,jerry]))

[ 5 10 15 20  2  4  6  8  3  5  7  9]


It can also be used for two-dimensional arrays:

In [63]:
toy = np.array([[5,15,25],
              [10,20,30]])

In [64]:
# concatenate along the first axis
np.concatenate([toy,toy])

array([[ 5, 15, 25],
       [10, 20, 30],
       [ 5, 15, 25],
       [10, 20, 30]])

In [65]:
# concatenate along the second axis (zero-indexed)
np.concatenate([toy,toy], axis=1)

array([[ 5, 15, 25,  5, 15, 25],
       [10, 20, 30, 10, 20, 30]])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

In [66]:
n = [2, 6, 8, 9, 5, 7, 3, 8, 1, 0, 6]
n1, n2, n3, n4 = np.split(x, [3, 5, 8,])
print(n1, n2, n3, n4)

[0.         0.05882353 0.11764706] [0.17647059 0.23529412] [0.29411765 0.35294118 0.41176471] [0.47058824 0.52941176 0.58823529 0.64705882 0.70588235 0.76470588
 0.82352941 0.88235294 0.94117647 1.         1.05882353 1.11764706
 1.17647059 1.23529412 1.29411765 1.35294118 1.41176471 1.47058824
 1.52941176 1.58823529 1.64705882 1.70588235 1.76470588 1.82352941
 1.88235294 1.94117647]


Notice that *N* split-points, leads to *N + 1* subarrays.
The related functions ``np.hsplit`` and ``np.vsplit`` are similar:

In [67]:
green = np.arange(15).reshape((3,5))
green

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
x,y = np.hsplit(green, [3])
print(x)
print(y)

[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
[[ 3  4]
 [ 8  9]
 [13 14]]


### Aggregates

For binary ufuncs, there are some interesting aggregates that can be computed directly from the object.
For example, if we'd like to *reduce* an array with a particular operation, we can use the ``reduce`` method of any ufunc.
A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

For example, calling ``reduce`` on the ``add`` ufunc returns the sum of all elements in the array:

In [69]:
blue = np.arange(2,11)
print(blue)
np.add.reduce(blue)

[ 2  3  4  5  6  7  8  9 10]


54

Similarly, calling ``reduce`` on the ``multiply`` ufunc results in the product of all array elements:

In [70]:
np.multiply.reduce(blue)

3628800

If we'd like to store all the intermediate results of the computation, we can instead use ``accumulate``:

In [71]:
np.add.accumulate(blue)

array([ 2,  5,  9, 14, 20, 27, 35, 44, 54], dtype=int32)

In [72]:
np.multiply.accumulate(blue)

array([      2,       6,      24,     120,     720,    5040,   40320,
        362880, 3628800], dtype=int32)